### ISSUE TITLE
[Question] Where are models downloaded to?

### ISSUE THREAD

**Issue by Zyin055** [peterwilli/sd-leap-booster#4]
I couldn't get the repo working when using `--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5` and now there's 4GB of files saved somewhere on my hard drive. Where are they saved so I can delete them?

**Comment by saltacc** [comment]
LEAP is based on top of the huggingface diffuers textual inversion trainer. The models are downloaded via huggingface and saved in huggingface's cache. You can find the location here https://huggingface.co/docs/transformers/installation#cache-setup

**Comment by Zyin055** [comment]
Thanks, found the folders where the data is saved:
`C:\Users\username\.cache\huggingface\hub\models--runwayml--stable-diffusion-v1-`
`C:\Users\username\.cache\huggingface\diffusers\models--runwayml--stable-diffusion-v1-5`
